apiVersion: v1
kind: Service
metadata:
  name: image-processing-service
spec:
  selector:
    app: image-processing-service
  ports:
  - protocol: "TCP"
    port: 5001
    targetPort: 5001
    nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-deployment
spec:
  selector:
    matchLabels:
      app: image-processing-service
  replicas: 1
  template:
    metadata:
      labels:
        app: image-processing-service
    spec:
      containers:
      - name: main-service
        image: chrisarrefall/image-processing-service:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
      nodeSelector:
        layer: entry
