apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: main-service
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
    nodePort: 30000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service-deployment
spec:
  selector:
    matchLabels:
      app: main-service
  replicas: 1
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
      - name: main-service
        image: chrisarrefall/main-service:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      nodeSelector:
        arch: arm64 
